-- SQL SCRIPT THAT CREATES A TABLE USERS WITH THREE ATRIBUTES: id, email AND name
DROP TABLE IF EXISTS users;

CREATE TABLE users(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255)
);