-- SQL SCRIPT THAT CREATES A TRIGGER THAT RESETS THE ATTRIBUTE VALID_EMAIL ONLY WHEN THE EMAIL HAS BEEN CHANGED.
CREATE TRIGGER reset_valid_email AFTER UPDATE ON users.email
FOR EACH ROW UPDATE users
SET valid_email = 0
WHERE email = NEW.email;