-- SQL SCRIPT THAT CREATES A STORED PROCEDURE COMPUTEAVERAGESCOREFORUSER THAT COMPUTES AND STORE THE AVERAGE SCORE FOR A STUDENT. NOTE: AN AVERAGE SCORE CAN BE A DECIMAL
DROP PROCEDURE IF EXISTS ComputeAverageScoreForUser;
DELIMETER $$
CREATE PROCEDURE ComputeAverageScoreForUser(IN user_id INT)
BEGIN
    DECLARE average_score FLOAT;
    SET average_score = (SELECT AVG(score) FROM correction AS C WHERE C.user_id=user_id);
    UPDATE users SET average_score = avg_score WHERE id=user_id;
END
$$
DELIMITER ;
